version: '3'

tasks:
  push:
    cmds:
      - pwd
      - git pull
      - git add .
      - |
        echo -n "[commit message]: "
        read message
        echo ""

        if [ ${message} ]; then
          git commit -m "quick commit, no new description, see the previous commit message."
        else
          git commit -m "${message}"
        fi
      - |
        git push
        echo -e "\n---git push is done.---\n"

