version: '3'

env:
  DEFAULT_COMMIT_MESSAGE: "quick commit, no new description, see the previous commit message."

tasks:
  push:
    cmds:
      - pwd
      - git add .
      - |
        echo -n "[commit message]: "
        read message
        echo ""
        if [ "{{.message}}" == "" ]; then
          git commit -m "{{.DEFAULT_COMMIT_MESSAGE}}"
        else
          git commit -m "{{.message}}"
        fi
      - |
        # git push
        echo -e "\n---git push is done.---\n"

