version: '3'

env:
  DEFAULT_COMMIT_MESSAGE: "quick commit, no new description, see the previous commit message."

tasks:
  push:
    cmds:
      - pwd
      - git add .
      - |
        if [ "{{.m}}" == "" ]; then
          git commit -m "{{.DEFAULT_COMMIT_MESSAGE}}"
        else
          git commit -m "{{.m}}"
        fi
      - git push
